spring:
  application:
    name: sample-server

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: loggers,health,info
  endpoint:
    loggers:
      enabled: true
